name: philip
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.9.1=hf036a51_0
  - aws-c-auth=0.9.0=h11bee3c_15
  - aws-c-cal=0.9.2=h80a239a_0
  - aws-c-common=0.12.3=h6e16a3a_0
  - aws-c-compression=0.3.1=hdea44ad_5
  - aws-c-event-stream=0.5.4=h01412b5_12
  - aws-c-http=0.10.2=ha1444c5_2
  - aws-c-io=0.20.1=h550966a_0
  - aws-c-mqtt=0.13.1=h90c2deb_3
  - aws-c-s3=0.8.3=hb3f0f26_0
  - aws-c-sdkutils=0.2.4=hdea44ad_0
  - aws-checksums=0.2.7=hdea44ad_1
  - aws-crt-cpp=0.32.10=h1b1c4c6_1
  - aws-sdk-cpp=1.11.510=hf939bc4_12
  - azure-core-cpp=1.14.0=h9a36307_0
  - azure-identity-cpp=1.10.0=ha4e2ba9_0
  - azure-storage-blobs-cpp=12.13.0=h3d2f5f1_1
  - azure-storage-common-cpp=12.8.0=h1ccc5ac_1
  - azure-storage-files-datalake-cpp=12.12.0=h86941f0_1
  - blosc=1.21.6=hd145fbb_1
  - bokeh=3.7.3=pyhd8ed1ab_0
  - bottleneck=1.5.0=py313h1492807_0
  - brotli=1.1.0=h6e16a3a_3
  - brotli-bin=1.1.0=h6e16a3a_3
  - brotli-python=1.1.0=py313h14b76d3_3
  - bzip2=1.0.8=hfdf4475_7
  - c-ares=1.34.5=hf13058a_0
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - cairo=1.18.4=h950ec3b_0
  - cartopy=0.24.0=py313h38cdd20_0
  - certifi=2025.7.14=pyhd8ed1ab_0
  - cffi=1.17.1=py313h49682b3_0
  - cftime=1.6.4=py313h8f4588c_1
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - contourpy=1.3.2=py313ha0b1807_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cytoolz=1.0.1=py313h63b0ddb_0
  - dask=2025.5.1=pyhd8ed1ab_0
  - dask-core=2025.5.1=pyhd8ed1ab_0
  - dav1d=1.2.1=h0dc2134_0
  - dbus=1.16.2=h27bd348_0
  - distributed=2025.5.1=pyhd8ed1ab_0
  - ffmpeg=7.1.1=gpl_h731c141_107
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h37eeddb_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.4=py313h717bdf5_0
  - freetype=2.13.3=h694c41f_1
  - fribidi=1.0.10=hbcb3906_0
  - fsspec=2025.5.1=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.12=ha587570_0
  - geos=3.13.1=h502464c_0
  - gflags=2.2.2=hac325c4_1005
  - glog=0.7.1=h2790a97_0
  - gmp=6.3.0=hf036a51_2
  - graphite2=1.3.14=h240833e_0
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.3.3=hb258ee5_0
  - hdf4=4.2.15=h8138101_7
  - hdf5=1.14.4=nompi_h1607680_105
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=h120a0e1_0
  - idna=3.10=pyhd8ed1ab_1
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - kiwisolver=1.4.8=py313h6d0c2b6_0
  - krb5=1.21.3=h37d8d59_0
  - lame=3.100=hb7f2c08_1003
  - lcms2=2.17=h72f5680_0
  - lerc=4.0.0=hcca01a6_1
  - libabseil=20250127.1=cxx17_h0e468a2_0
  - libaec=1.1.4=ha6bc127_0
  - libarrow=20.0.0=h7601d43_8_cpu
  - libarrow-acero=20.0.0=hdc53af8_8_cpu
  - libarrow-dataset=20.0.0=hdc53af8_8_cpu
  - libarrow-substrait=20.0.0=ha37b807_8_cpu
  - libass=0.17.4=h87c4fc2_0
  - libblas=3.9.0=31_h7f60823_openblas
  - libbrotlicommon=1.1.0=h6e16a3a_3
  - libbrotlidec=1.1.0=h6e16a3a_3
  - libbrotlienc=1.1.0=h6e16a3a_3
  - libcblas=3.9.0=31_hff6cab4_openblas
  - libcrc32c=1.1.2=he49afe7_0
  - libcurl=8.14.1=h5dec5d8_0
  - libcxx=20.1.7=hf95d169_0
  - libdeflate=1.24=hcc1b750_0
  - libedit=3.1.20250104=pl5321ha958ccf_0
  - libev=4.33=h10d778d_2
  - libevent=2.1.12=ha90c15b_1
  - libexpat=2.7.1=h21dd04a_0
  - libffi=3.4.6=h281671d_1
  - libfreetype=2.13.3=h694c41f_1
  - libfreetype6=2.13.3=h40dfd5c_1
  - libgfortran=15.1.0=h5f6db21_0
  - libgfortran5=15.1.0=hfa3c126_0
  - libglib=2.84.2=h3139dbc_0
  - libgoogle-cloud=2.36.0=h777fda5_1
  - libgoogle-cloud-storage=2.36.0=h3397294_1
  - libgrpc=1.71.0=h7d722e6_1
  - libhwloc=2.12.1=default_h8c32e24_1000
  - libiconv=1.18=h4b5e92a_1
  - libintl=0.25.1=h3184127_1
  - libjpeg-turbo=3.1.0=h6e16a3a_0
  - liblapack=3.9.0=31_h236ab99_openblas
  - liblzma=5.8.1=hd471939_2
  - libmpdec=4.0.0=h6e16a3a_0
  - libnetcdf=4.9.2=nompi_hd7a758f_116
  - libnghttp2=1.64.0=hc7306c3_0
  - libogg=1.3.5=he3325bb_1
  - libopenblas=0.3.29=openmp_hbf64a52_0
  - libopentelemetry-cpp=1.21.0=h30c661f_0
  - libopentelemetry-cpp-headers=1.21.0=h694c41f_0
  - libopenvino=2025.2.0=h84fdd48_0
  - libopenvino-auto-batch-plugin=2025.2.0=hf8d533f_0
  - libopenvino-auto-plugin=2025.2.0=hf8d533f_0
  - libopenvino-hetero-plugin=2025.2.0=h035ecc0_0
  - libopenvino-intel-cpu-plugin=2025.2.0=h84fdd48_0
  - libopenvino-ir-frontend=2025.2.0=h035ecc0_0
  - libopenvino-onnx-frontend=2025.2.0=h84dae0a_0
  - libopenvino-paddle-frontend=2025.2.0=h84dae0a_0
  - libopenvino-pytorch-frontend=2025.2.0=hb639f4d_0
  - libopenvino-tensorflow-frontend=2025.2.0=hbe29116_0
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hb639f4d_0
  - libopus=1.5.2=he3325bb_0
  - libparquet=20.0.0=h283e888_8_cpu
  - libpng=1.6.49=h3c4a55f_0
  - libprotobuf=5.29.3=h1c7185b_1
  - libre2-11=2025.06.26=hfc00f1c_0
  - librsvg=2.58.4=h21a6cfa_3
  - libsqlite=3.50.1=he7d56d0_6
  - libssh2=1.11.1=hed3591d_0
  - libthrift=0.21.0=h75589b3_0
  - libtiff=4.7.0=h1167cee_5
  - libusb=1.0.29=h2287256_0
  - libutf8proc=2.10.0=h5b79583_0
  - libvorbis=1.3.7=ha059160_2
  - libvpx=1.14.1=hf036a51_0
  - libwebp-base=1.5.0=h6cf52b4_0
  - libxcb=1.17.0=hf1f96e2_0
  - libxml2=2.13.8=h93c44a6_0
  - libzip=1.11.2=h31df5bb_0
  - libzlib=1.3.1=hd23fc13_2
  - littleutils=0.2.4=pyhd8ed1ab_1
  - llvm-openmp=20.1.7=ha54dae1_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.4=py313hc9bb01a_0
  - lz4-c=1.10.0=h240833e_1
  - markupsafe=3.0.2=py313h717bdf5_1
  - matplotlib=3.10.3=py313habf4b1d_0
  - matplotlib-base=3.10.3=py313he981572_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.1=py313ha0b1807_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=1.45.0=pyhe01879c_0
  - ncurses=6.5=h0622a9a_3
  - netcdf4=1.7.2=nompi_py313hf019e8c_101
  - nlohmann_json=3.12.0=h92383a6_0
  - numpy=2.3.0=py313hc518a0f_0
  - openh264=2.6.0=h4883158_0
  - openjpeg=2.5.3=h7fd6d84_0
  - openssl=3.5.1=hc426f3f_0
  - orc=2.1.2=h82caab2_0
  - outdated=0.2.2=pyhd8ed1ab_2
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.0=py313h2e7108f_0
  - pandas-flavor=0.7.0=pyhd8ed1ab_0
  - pango=1.56.4=h6ef8af8_0
  - partd=1.4.2=pyhd8ed1ab_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.45=hf733adb_0
  - pillow=11.2.1=py313h0c4f865_0
  - pingouin=0.5.5=pyhd8ed1ab_1
  - pip=25.1.1=pyh145f28c_0
  - pixman=0.46.4=h6f2c7e4_0
  - proj=9.6.2=h5273da6_0
  - prometheus-cpp=1.3.0=h7802330_0
  - psutil=7.0.0=py313h63b0ddb_0
  - pthread-stubs=0.4=h00291cd_1002
  - pugixml=1.15=h46091d4_0
  - pyarrow=20.0.0=py313habf4b1d_0
  - pyarrow-core=20.0.0=py313hc71e1e6_0_cpu
  - pycparser=2.22=pyh29332c3_1
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyproj=3.7.1=py313h0718947_1
  - pyshp=2.3.1=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.5=hc3a4c56_102_cp313
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=7_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py313h717bdf5_2
  - qhull=2020.2=h3c5361c_5
  - re2=2025.06.26=ha5e900a_0
  - readline=8.2=h7cca4af_2
  - requests=2.32.4=pyhd8ed1ab_0
  - scikit-learn=1.7.0=py313hedeaec8_1
  - scipy=1.15.2=py313h7e69c36_0
  - sdl2=2.32.54=h92383a6_0
  - sdl3=3.2.18=hc0b302d_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - shapely=2.1.1=py313h11e92a8_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=haf3c120_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - sqlite=3.50.1=h22fafd5_6
  - statsmodels=0.14.4=py313h8f4588c_0
  - svt-av1=3.0.2=h240833e_0
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tbb=2022.2.0=hc025b3e_0
  - tblib=3.1.0=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=hf689a15_2
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.5.1=py313h63b0ddb_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - x264=1!164.3095=h775f41a_2
  - x265=3.5=hbb4e6a2_3
  - xarray=2025.6.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h6e16a3a_0
  - xorg-libxdmcp=1.1.5=h00291cd_0
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - yaml=0.2.5=h0d85af4_2
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hd23fc13_2
  - zstandard=0.23.0=py313h63b0ddb_2
  - zstd=1.5.7=h8210216_2
prefix: /opt/anaconda3/envs/philip
